version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./../../data/dev/rabbitmq:/var/lib/rabbitmq
    networks:
      - dev_environment
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
  postgresql:
    image: postgres:13.5-alpine
    container_name: postgresql
    hostname: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #POSTGRES_DB: dev
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - dev_environment
    volumes:
      - ./postgresql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./../../data/dev/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c stats_temp_directory=/tmp
  redis:
    image: redis:6.2.5-alpine
    container_name: redis_container
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./../../data/dev/redis:/data
    networks:
      - dev_environment
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    restart: always
  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: php
    hostname: ${HOSTNAME:-php}
    ports:
      - 9000:9000
      - 9005:9005
    environment:
      - PHP_ENABLE_XDEBUG=0
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    volumes:
      - ./../../:/app
    working_dir: /app
    networks:
      - dev_environment
    depends_on:
      - redis
      - postgresql
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./../../:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/php-fpm:/etc/nginx/php-fpm
    depends_on:
      - php
    restart: always
    ports:
      - 80:80
    networks:
      - dev_environment
networks:
  dev_environment:
    name: dev_network
