doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
          translation_format_types: 'string'
          media_categories: 'string'
          point: 'string'
          _int8: 'string'
          user_types: 'string'
          accessibility_types: 'string'
          xml: 'string'
          day_type: 'string'
          identificator_types: 'string'
          user_group_visibility_types: 'string'
          regionality_text_direction_type: 'string'
          site_types: 'string'
          properties_data_types: 'string'
          queue_action: 'string'
          user_role_visibility_types: 'string'
          fiscalization_level_types: 'string'
          auth_pair_types: 'string'
          contact_types: 'string'
          invoice_item_type: 'string'
          invoice_item_payment_type: 'string'
          permission_types: 'string'
          modification_operations: 'string'
          action_types: 'string'
          tag_types: 'string'
          product_view_status: 'string'
          enum: string # <- this is what you need!
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
